apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-108
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:reshmipatro/test.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
