apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-110
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:reshmipatro/test.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://192.168.56.110:6443
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
